### PR TITLE
Add CIS 1.1 scored scripts

### PR DESCRIPTION
**Pull request by bordoloih**

### CODE REVIEW

**Review by satya-rajesh — COMMENTED** [review]
There is a failure:
TASK [cis : 1.1.15 Mount /dev/shm] *********************************************
fatal: [/root/testroot]: FAILED! => {"changed": false, "msg": "Failed to find required executable mount in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}

Other tests did not run completely due to above failure.

**Comment by bordoloih** [comment]
> fatal: [/root/testroot]: FAILED! => {"changed": false, "msg": "Failed to find required executable mount in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}

Please install package util-linux in the chroot

**Comment by satya-rajesh** [comment]
> > fatal: [/root/testroot]: FAILED! => {"changed": false, "msg": "Failed to find required executable mount in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
> 
> Please install package util-linux in the chroot

Manual installation should not be performed, please install here which does as chroot:
ansible-security-hardening/examples/Dockerfile

The travis-CI is broken:
https://travis-ci.org/vmware/ansible-security-hardening/builds/655670888?utm_source=github_status&utm_medium=notification

**Comment by satya-rajesh** [comment]
Please fix this:
TASK [cis : 1.1.2 verify if /tmp is mounted] ***********************************
fatal: [/root/testroot]: FAILED! => {"changed": true, "cmd": "mount | grep '\\s/tmp\\s'", "delta": "0:00:00.099928", "end": "2020-03-05 06:19:59.481588", "msg": "non-zero return code", "rc": 1, "start": "2020-03-05 06:19:59.381660", "stderr": "mount: failed to read mtab: No such file or directory", "stderr_lines": ["mount: failed to read mtab: No such file or directory"], "stdout": "", "stdout_lines": []}

https://travis-ci.org/vmware/ansible-security-hardening/builds/658546966?utm_source=github_status&utm_medium=notification

**Review by satya-rajesh — COMMENTED** [review]
Overall looks good to me, some minor comments:

TASK [cis : 1.1.22 Check if autofs is installed] *******************************
fatal: [/root/testroot]: FAILED! => {"changed": false, "cmd": "rpm -q autofs", "msg": "[Errno 2] No such file or directory: 'rpm': 'rpm'", "rc": 2}
...ignoring

Is rc: 2 expected ? If it is expected, can we compare against result.rc == 2.
Once this change is done, ignoreerrors=True can be removed.

PLAY RECAP *********************************************************************
/root/testroot             : ok=296  changed=83   unreachable=0    failed=0    skipped=184  rescued=0    ignored=1  

Please also update README.md file similar to that of changes done in Dockerfile.

**Review by satya-rajesh — APPROVED** [review]

**Pull request merged**
